# Generated by Django 5.0.2 on 2024-04-10 19:37

import django.utils.timezone
import django_google_maps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=django_google_maps.fields.AddressField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='54.504642559881646,-105.02634999999995', max_length=100),
        ),
    ]
