# Generated by Django 5.0.2 on 2024-03-25 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycle'), ('Truck', 'Truck'), ('Van', 'Van'), ('SUV', 'Suv'), ('Other', 'Other')], default='Other', max_length=10)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
